/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: '#0f62fe',
        'primary-on': '#ffffff',
        'blue-60': '#0043ce',
        'blue-80': '#002d9c',
        'blue-hover': '#0050e6',
        ink: '#161616',
        'ink-muted': '#525252',
        'ink-subtle': '#8c8c8c',
        canvas: '#ffffff',
        'surface-1': '#f4f4f4',
        'surface-2': '#e0e0e0',
        'inverse-canvas': '#161616',
        'inverse-surface-1': '#262626',
        'inverse-ink': '#ffffff',
        'inverse-ink-muted': '#c6c6c6',
        hairline: '#e0e0e0',
        'hairline-strong': '#161616',
        'semantic-success': '#24a148',
        'semantic-warning': '#f1c21b',
        'semantic-error': '#da1e28',
        'semantic-info': '#0f62fe',
      },
      fontFamily: {
        sans: ['IBM Plex Sans', 'Helvetica Neue', 'Arial', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['76px', { lineHeight: '1.17', fontWeight: '300', letterSpacing: '-0.5px' }],
        'display-lg': ['60px', { lineHeight: '1.17', fontWeight: '300', letterSpacing: '-0.4px' }],
        'display-md': ['42px', { lineHeight: '1.20', fontWeight: '300' }],
        headline: ['32px', { lineHeight: '1.25', fontWeight: '400' }],
        'card-title': ['24px', { lineHeight: '1.33', fontWeight: '400' }],
        subhead: ['20px', { lineHeight: '1.40', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.50', fontWeight: '400' }],
        body: ['16px', { lineHeight: '1.50', fontWeight: '400', letterSpacing: '0.16px' }],
        'body-sm': ['14px', { lineHeight: '1.29', fontWeight: '400', letterSpacing: '0.16px' }],
        'body-emphasis': ['14px', { lineHeight: '1.29', fontWeight: '600', letterSpacing: '0.16px' }],
        caption: ['12px', { lineHeight: '1.33', fontWeight: '400', letterSpacing: '0.32px' }],
        'btn-label': ['14px', { lineHeight: '1.29', fontWeight: '400', letterSpacing: '0.16px' }],
      },
      borderRadius: {
        none: '0px',
        xs: '2px',
        sm: '4px',
        md: '6px',
        lg: '8px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
      boxShadow: {
        none: 'none',
        focus: '0 0 0 2px #0f62fe',
      },
    },
  },
  plugins: [],
}
